evervault/attestation-doc-validation

.github/workflows/publish-packages.yml
Cargo.lock
attestation-doc-validation/Cargo.toml

Need to be able to publish the rust crate to crates.io, so added a new workflow, and bumped the crate version to 0.4.0
- On push to rust/v<semver>, we will deploy the rust crate to crates.io. While the tag pattern isn't the cleanest, we need to be able to release the crate in isolation, so we can update the dependencies of the bindings.
- This pattern will extend to `node/v...` and `python/v...`
- The workflow does some validation on the crate before publishing
- ensure the crate version matches the tag
- ensure the tests are passing
- perform a dry run publish
- publish following additional approval
- The `public-release` environment is used to gate publishing to crates.io behind an additional approval by a member of @evervault/spectre

Add workflow for publishing the rust crate on tag

---

.github/workflows/publish-packages.yml

Error in yaml syntax
- runs-on cannot be defined outside of individual jobs
- jobs didn't enforce ordering, so added needs to each job

correct workflow syntax and enforce job ordering

---

.github/workflows/publish-packages.yml

Toolchain was not specified, but is a required input
Add parameters to toolchain action where missing

add parameters to rust toolchain step

---

.github/workflows/publish-packages.yml

Action is pretty opaque
Add a log to help debug the release action

add log of received versus expected

---

.github/workflows/publish-packages.yml

The version tags aren't matching because the one returned from the cargo toml is in quotes
Update action to strip quotes from the version to allow matching

Clean quote returned from Cargo

---

.github/workflows/publish-packages.yml

Cargo doesn't expect the token to be passed directly to the login command
Correct args

Correct passing of token to cargo

---

.github/workflows/publish-packages.yml

Login command was incorrectly formatted, but also unnecessary
Pass token straight to publish

Pass token directly to publish command

---

attestation-doc-validation/Cargo.toml

Cargo restricts keywords to a max length of 20, confidetnial-computing is 22
Remove confidential computing keyword, use enclaves

Reduce length of cargo keywords

---

Cargo.lock
attestation-doc-validation/Cargo.toml
attestation-doc-validation/src/attestation_doc.rs
attestation-doc-validation/src/lib.rs
attestation-doc-validation/src/nsm/error.rs
attestation-doc-validation/src/nsm/mod.rs
attestation-doc-validation/src/nsm/nsm_api.rs

We can recreate the types we need from the nsm api without a direct dependency which will remove a transitive dependency on nix
Recreate the types that we depend on from the nsm api and remove the dep

Remove transitive nix dependency

---

Cargo.lock
attestation-doc-validation/src/attestation_doc.rs
attestation-doc-validation/src/error.rs

Need attestation doc parsing and challenge validation public for use in E3
- Make functions public
- Move validation into `decode_attestation_document` and keep private

Make attestation doc functions public

---

.github/workflows/publish-packages.yml

Release is breaking at the moment due to a dependency version mismatch
Don't include dependencies in cargo metadata command

Add --no-dep to cargo metadata for rust release

---

attestation-doc-validation/src/attestation_doc.rs
attestation-doc-validation/src/lib.rs
attestation-doc-validation/tests/live_cert_validation.rs
test-specs/valid_attestation_doc_check_pcr8_only_time_sensitive.json

- There's no function exposed to validate an attestation doc that isn't embedded in a cert currently
- At the moment if you use the crate it's only possible to access the PCRs as a BTreeMap. To save repeating the same code elsewhere it's easier to expose the extraction logic
- Add function that parses and validates any attestation doc and returns a result
- Expose `get_prs` which returns the PCRs struct

Validate any attestation doc and parse PCRs easily

---

Cargo.lock
attestation-doc-validation/Cargo.toml

The crate needs to be released
Bump version to 0.4.3

Bump to version 0.4.3

---

Cargo.lock
attestation-doc-validation/Cargo.toml

We published the corresponding semver tag to the previous version, this blocks our bindings from depending on the beta (auto bumped to 0.4.2)
Move beta tag to next minor version

Bump beta version

---

.github/workflows/build-and-deploy-python-bindings.yml

Python workflow needs to run when a tag is pushed in the form `python/v<semver>`
Add event for tag push

Update python workflow to run on tag push

---

python-attestation-bindings/pyproject.toml

Want to support the same python version range as the existing evervault python sdk
Drop min version to 3.6, reduce min version of maturin to include python 3.6 support.

Broaden python support in attestation

---

Cargo.lock
attestation-doc-validation/Cargo.toml
attestation-doc-validation/src/attestation_doc.rs
attestation-doc-validation/src/error.rs

The errors for invalid attestation docs are very vague as they're currently in a single boolean
Return more descriptive error

Improve attestation doc validation errors

---

.github/workflows/build-and-deploy-node-bindings.yml
.github/workflows/build-and-deploy-python-bindings.yml
.github/workflows/publish-rust-crate.yml

Version check is failing, as there's an extra `\n`
Don't parse the version into a github variable first. Try to just use `${GITHUB_REF:16}` directly

Fix version assertion in publish actions

---

Cargo.lock
node-attestation-bindings/Cargo.toml
node-attestation-bindings/__test__/index.spec.mjs
node-attestation-bindings/index.d.ts
node-attestation-bindings/package.json
node-attestation-bindings/src/lib.rs
python-attestation-bindings/Cargo.toml
python-attestation-bindings/pyproject.toml
python-attestation-bindings/src/lib.rs

Our SDKs will have the ability to try multiple sets of PCRs, to allow for rollover of certs/containers
* Take in a list of  PCR objects instead of a single one. To validate a single set of PCRs, you just pass in a single-element list
* If the list of PCRs to check is empty, return true
* If any of the PCRs in the list match, return true
* If they all fail, return the last error
* Bump versions to non-beta

Update bindings to take in multiple sets of PCRs

---

.github/workflows/build-and-deploy-node-bindings.yml

The `aarch64-linux-musl` tests are passing, but not exiting. This is blocking the publishing of node bindings.
Comment out `test-linux-aarch64-musl-binding`

Ignore aarch64-linux-musl tests for node bindings

---

.github/workflows/build-and-deploy-python-bindings.yml

Using the wrong character offset when parsing the version out of the tag. This is blocking Python bindings deployments
Use correct character offset when parsing python version

Fix python version parsing

---

Cargo.lock
attestation-doc-validation/Cargo.toml
attestation-doc-validation/src/error.rs
attestation-doc-validation/src/lib.rs
node-attestation-bindings/src/lib.rs

Support new attestation flow
Add a new method to the `attestation-doc-validation` crate `validate_attestation_doc_against_cert`
See https://github.com/evervault/cages/pull/73/files for encoding of challenge
Can merge #60 after this to add node bindings

Add new attestation flow validator

---

node-attestation-bindings/package.json

Bump node binding version for next release
Bump to 0.3.0

Bump node bindings minor version

---

swift-attestation-bindings/ios/AttestationBindingsRustFFI.h
swift-attestation-bindings/src/lib.rs

Cages have a trusted cert now but the attestation doc isn't embedded in the cert. This mean the AD has to be pulled from the cage and passed into the attestation function.
Added `attest_cage()` which takes in the cert, the expected_pcrs and the attestation document (already pulled from the cage). Then use the `validate_attestation_doc_against_cert` method from the rust bindings to validate that the public key of the cert matches the public key embedded in the attestation document given to the function.

[SPE-855] Add new swift attest_cage method for attesting against trusted cert 

---

README.md
python-attestation-bindings/pyproject.toml
python-attestation-bindings/src/lib.rs
python-attestation-bindings/tests/test_attestation.py

Its more helpful to see the error then return a log and bool
Raise error instead of false

Raise error on invalid pcrs

---

Cargo.lock
attestation-doc-validation/Cargo.toml

Serde bug was fixed in aws-nitro-enclaves-cose https://github.com/awslabs/aws-nitro-enclaves-cose/pull/66/files
Unpin serde version

Unpin serde version

---

.github/workflows/build-and-deploy-python-bindings.yml
python-attestation-bindings/pyproject.toml

Bindings are missing for python builds on arm linux. The default behaviour was just building for x86 so we weren't releasing wheels for every os & arch
Add steps that explicitly target builds for arm linux targets

Explicitly build for arm linux targets

---

kotlin-attestation-bindings/src/bindings.udl
kotlin-attestation-bindings/src/lib.rs
kotlin-attestation-bindings/src/uniffi/bindings/bindings.kt

You can now pass a single PCR to attest a connection to an enclave
- Update the UDL file to use Option for pcrs
- Change the PCR struct to use new type
- Regenerate the Kotlin bindings

feat: make PCRs optional

---

kotlin-attestation-bindings/src/bindings.udl
kotlin-attestation-bindings/src/lib.rs
kotlin-attestation-bindings/src/uniffi/bindings/bindings.kt

Updating kotlin attestation bindings to use enclave instead of cage
- refactor references to Cage

update remove references to cage

---

node-attestation-bindings/package.json

V1 release of node bindings under new namespace
Update package version to v1.

Prepare node bindings for v1 release

---

.github/workflows/build-and-deploy-node-bindings.yml
Cargo.lock
attestation-doc-validation/Cargo.toml
attestation-doc-validation/src/cert.rs
attestation-doc-validation/src/error.rs
attestation-doc-validation/src/lib.rs

When an attestation doc is rejected for an untrusted cert chain, we currently return a generic error message which gives no insight into the root cause.
Update the returned error for an invalid trust chain and embed the serialized error from the webpki crate.

Add more context to untrusted cert error

---

.github/workflows/build-and-deploy-node-bindings.yml
.github/workflows/build-and-deploy-python-bindings.yml
.github/workflows/lint-and-test.yml
.github/workflows/publish-rust-crate.yml
Cargo.lock
attestation-doc-validation/Cargo.toml
attestation-doc-validation/src/nsm/der.rs

Rust project is a minor behind on several of the rust crypto projects which is leading to versioning conflicts when integrating in new rust projects with conflicting nested deps.
Bump dependencies to most recent minor

Update crypto dependencies of rust project

---

wasm-attestation-bindings/README.md
wasm-attestation-bindings/example.html
wasm-attestation-bindings/src/lib.rs

Initial impl of the PCR container in rust exposed to JS was leaking the FFI interface through it's naming convention (snake case, and `Js` prefix on types). It also omitted the constructor, which rendered the PCRs inaccessible.
Add aliases to improve naming of exposed JS interface:
- `JsPCRs` -> `PCRs`
- `PCRs.pcr_X` -> `PCRs.pcrX`
- Expose new `empty` API for `PCRs` to avoid passing many `undefined`s to the constructor.
- Add README discussing the difference in trust model for browser vs backend clients
- Add tiny html client example.

Alias Rust types to have JS Friendly casing, constructors and setters

---

attestation-doc-validation/Cargo.toml

Version needs to match next release
Bump rust crate version to 0.10.0

Update Cargo.toml version to 0.10.0

---

python-attestation-bindings/src/lib.rs

Python bindings still referenced Cages in their entrypoint
Create new attest_enclave function to replace attest_cage

chore: expose attest_enclave function to replace attest_cage

---

python-attestation-bindings/pyproject.toml

The python bindings are being prepped for release, so need to be moved to 0.4.0
Bump version in pyproject.toml

chore: update python version for release

---

.github/workflows/build-and-deploy-python-bindings.yml

Download artifact workflow was incorrectly configured, attempting to download by name and pattern.
Removed name option

fix: python release workflow attempted to download all artifacts by by pattern

---

.github/workflows/build-and-deploy-wasm-bindings.yml

The release build didnt trigger because the tag was missing
Add tag trigger to workflow

Add tag trigger for wasm

---

.github/workflows/build-and-deploy-wasm-bindings.yml

Its defaulting to 1.81 so the crate isn't building
Fix rust version like in build step

Fix rust version to 1.79 for wasm release
